# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      
      - name: version check
        run: |
          export CHNGVER=$(grep -P -o '(?<=## \[).*(?=\])' -m1 CHANGELOG.md); 
          echo "CHANGELOG VERSION: $CHNGVER"
          export TAGVER=${{ steps.get-latest-tag.outputs.tag }}; 
          echo "TAG VERSION: $TAGVER"
          if [ "$CHNGVER" = "$TAGVER" ]; then
              echo "No changelog update."
              exit 1
          else
              echo "Changelog updated."
          fi
  test-run:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/incoresemi/docker-images/compliance:latest 
    steps:
      - uses: actions/checkout@v2
      - name: run
        run: |
          apt-get install python3-dev
          pip3 install riscof
          git clone https://gitlab.com/incoresemi/riscof-plugins.git 
          riscof --config ./.github/config/rv32.ini run --suite ./riscv-test-suite --env ./riscv-test-suite/env --work-dir ./rv32_work
          riscof --config ./.github/config/rv64.ini run --suite ./riscv-test-suite --env ./riscv-test-suite/env --work-dir ./rv64-work
